"""Interactive setup command for generating .env configuration.

Two flows:
  - simple (default): asks only for PRIMARY_API_KEY, model, and whether to
    configure a separate escalation tier. Writes sensible defaults for
    everything else (matching .env.example).
  - advanced (--advanced): asks every knob, with defaults shown.
"""

import os
from pathlib import Path


# ─── Default values applied when the user accepts simple-mode defaults.
# Single source of truth shared with .env.example below.
SIMPLE_DEFAULTS = {
    "PRIMARY_BASE_URL": "",
    "PRIMARY_AUTH_TOKEN": "",
    "PRIMARY_MODEL": "claude-opus-4-7",
    "SECONDARY_BASE_URL": "",
    "SECONDARY_API_KEY": "",
    "SECONDARY_AUTH_TOKEN": "",
    "SECONDARY_MODEL": "",       # populated only if user opts into escalation tier
    "SECONDARY_BUDGET": "125",
    "AUTOFIX": "true",
    "EXPLORATION": "true",
    "RECURSE": "",
    "NO_BYPASS": "",
    "SILENT": "",
    "RECORDING": "true",
    "SAVE_SPECIFICATION": "true",
    "SAVE_SEMIFORMALIZATION": "true",
    "GENERATION_BUDGET": "",
    "SEMIFORMALIZATION_BUDGET": "",
    "EXPLORATION_BUDGET": "",
    "SOURCE_SCAN_BUDGET": "",
    "FORMALIZATION_BUDGET": "",
    "CRITIC_BUDGET": "",
    "VALIDATION_BUDGET": "",
    "MAX_CRITIC_ITERATIONS": "",
    "MAX_VALIDATION_ITERATIONS": "",
    "RESOLVER_MAX_RETRIES": "",
    "FORUM_PORT": "6367",
    "LEAN_LSP_PORT": "6368",
    "SDK_MESSAGE_IDLE_TIMEOUT": "600",
    "MAX_LSP_RESTARTS_BEFORE_DEGRADE": "2",
    "TOOL_RESULT_MAX_CHARS": "50000",
    "CLAUDE_CODE_STREAM_CLOSE_TIMEOUT": "180000",
    "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "",
}


def _prompt(prompt: str, default: str = "", secret: bool = False) -> str:
    display = f"{prompt} [{default}]: " if default else f"{prompt}: "
    if secret:
        import getpass
        value = getpass.getpass(display)
    else:
        value = input(display)
    return value.strip() if value.strip() else default


def _prompt_bool(prompt: str, default: bool = False) -> bool:
    default_str = "Y/n" if default else "y/N"
    value = input(f"{prompt} [{default_str}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes", "true", "1")


def _write_env(output_path: str, env_vars: dict) -> Path:
    """Write a grouped, commented .env mirroring .env.example's structure."""
    output_file = Path(output_path)

    def _line(key: str) -> str:
        v = env_vars.get(key, "")
        return f"{key}={v}\n" if v else f"# {key}=\n"

    with output_file.open("w") as f:
        f.write("# Unity Agent configuration — generated by `unity setup`.\n")
        f.write("# See .env.example for the full reference with comments per variable.\n\n")

        f.write("# ── Primary (required) ──\n")
        for key in ("PRIMARY_API_KEY", "PRIMARY_MODEL",
                    "PRIMARY_BASE_URL", "PRIMARY_AUTH_TOKEN"):
            f.write(_line(key))

        f.write("\n# ── Secondary / escalation tier ──\n")
        for key in ("SECONDARY_API_KEY", "SECONDARY_MODEL",
                    "SECONDARY_BASE_URL", "SECONDARY_AUTH_TOKEN",
                    "SECONDARY_BUDGET"):
            f.write(_line(key))

        f.write("\n# ── Per-phase budgets (USD; blank = unlimited) ──\n")
        for key in ("GENERATION_BUDGET", "SEMIFORMALIZATION_BUDGET",
                    "EXPLORATION_BUDGET", "SOURCE_SCAN_BUDGET",
                    "FORMALIZATION_BUDGET", "CRITIC_BUDGET",
                    "VALIDATION_BUDGET"):
            f.write(_line(key))

        f.write("\n# ── Pipeline flags ──\n")
        for key in ("AUTOFIX", "EXPLORATION", "RECURSE", "NO_BYPASS",
                    "SILENT", "RECORDING",
                    "SAVE_SPECIFICATION", "SAVE_SEMIFORMALIZATION"):
            f.write(_line(key))

        f.write("\n# ── Iteration / retry caps ──\n")
        for key in ("MAX_CRITIC_ITERATIONS", "MAX_VALIDATION_ITERATIONS",
                    "RESOLVER_MAX_RETRIES"):
            f.write(_line(key))

        f.write("\n# ── Ports ──\n")
        for key in ("FORUM_PORT", "LEAN_LSP_PORT"):
            f.write(_line(key))

        f.write("\n# ── Advanced ──\n")
        for key in ("SDK_MESSAGE_IDLE_TIMEOUT",
                    "MAX_LSP_RESTARTS_BEFORE_DEGRADE",
                    "TOOL_RESULT_MAX_CHARS",
                    "CLAUDE_CODE_STREAM_CLOSE_TIMEOUT",
                    "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"):
            f.write(_line(key))

    return output_file


def _run_simple(env_vars: dict) -> None:
    """Minimal flow: just the keys + opt-in escalation tier. Everything else
    inherits the .env.example defaults already in env_vars."""
    print("\n─── Primary API access (required) ───\n")
    env_vars["PRIMARY_API_KEY"] = _prompt(
        "Primary API key",
        os.getenv("PRIMARY_API_KEY", ""),
        secret=True,
    )
    env_vars["PRIMARY_MODEL"] = _prompt(
        "Primary model", env_vars["PRIMARY_MODEL"]
    )
    env_vars["PRIMARY_BASE_URL"] = _prompt(
        "Primary base URL (blank = api.anthropic.com)",
        env_vars["PRIMARY_BASE_URL"],
    )
    env_vars["PRIMARY_AUTH_TOKEN"] = _prompt(
        "Primary auth token (blank for x-api-key auth)",
        env_vars["PRIMARY_AUTH_TOKEN"], secret=True,
    )

    print("\n─── Escalation tier (optional) ───")
    print("If left unset, escalation reuses the primary credentials. Skip "
          "this if you don't want a separate model for stuck chunks.\n")
    if _prompt_bool("Configure a separate escalation tier", False):
        env_vars["SECONDARY_API_KEY"] = _prompt(
            "Secondary API key", env_vars["SECONDARY_API_KEY"], secret=True
        )
        env_vars["SECONDARY_MODEL"] = _prompt(
            "Secondary model", "claude-opus-4-7"
        )
        env_vars["SECONDARY_BASE_URL"] = _prompt(
            "Secondary base URL (blank = api.anthropic.com)",
            env_vars["SECONDARY_BASE_URL"],
        )
        env_vars["SECONDARY_AUTH_TOKEN"] = _prompt(
            "Secondary auth token", env_vars["SECONDARY_AUTH_TOKEN"], secret=True,
        )
    else:
        # User declined; don't leave a model identifier dangling.
        env_vars["SECONDARY_MODEL"] = ""


def _run_advanced(env_vars: dict) -> None:
    """Full flow: every knob with sensible defaults from env_vars."""
    print("\n─── Primary tier ───\n")
    env_vars["PRIMARY_BASE_URL"] = _prompt(
        "Primary base URL", os.getenv("PRIMARY_BASE_URL", env_vars["PRIMARY_BASE_URL"])
    )
    env_vars["PRIMARY_API_KEY"] = _prompt(
        "Primary API key", os.getenv("PRIMARY_API_KEY", ""), secret=True,
    )
    env_vars["PRIMARY_AUTH_TOKEN"] = _prompt(
        "Primary auth token (optional)",
        os.getenv("PRIMARY_AUTH_TOKEN", env_vars["PRIMARY_AUTH_TOKEN"]),
        secret=True,
    )
    env_vars["PRIMARY_MODEL"] = _prompt("Primary model", env_vars["PRIMARY_MODEL"])

    print("\n─── Secondary tier (escalation) ───\n")
    env_vars["SECONDARY_BASE_URL"] = _prompt(
        "Secondary base URL", os.getenv("SECONDARY_BASE_URL", env_vars["SECONDARY_BASE_URL"])
    )
    env_vars["SECONDARY_API_KEY"] = _prompt(
        "Secondary API key", os.getenv("SECONDARY_API_KEY", ""), secret=True
    )
    env_vars["SECONDARY_AUTH_TOKEN"] = _prompt(
        "Secondary auth token (optional)",
        os.getenv("SECONDARY_AUTH_TOKEN", env_vars["SECONDARY_AUTH_TOKEN"]),
        secret=True,
    )
    env_vars["SECONDARY_MODEL"] = _prompt("Secondary model", env_vars["SECONDARY_MODEL"])

    print("\n─── Pipeline flags ───\n")
    env_vars["AUTOFIX"] = "true" if _prompt_bool("Enable autofix", True) else ""
    env_vars["EXPLORATION"] = "true" if _prompt_bool("Enable exploration phase", True) else ""
    env_vars["RECURSE"] = "true" if _prompt_bool("Enable recursive child unity runs", False) else ""
    env_vars["NO_BYPASS"] = "true" if _prompt_bool("Require permission for edits (no bypass)", False) else ""
    env_vars["SILENT"] = "true" if _prompt_bool("Silent mode (redirect to log files)", False) else ""
    env_vars["RECORDING"] = "true" if _prompt_bool("Tee output to log files", True) else ""
    env_vars["SAVE_SPECIFICATION"] = "true" if _prompt_bool("Keep generated IR after run", True) else ""
    env_vars["SAVE_SEMIFORMALIZATION"] = "true" if _prompt_bool("Keep semiformal/ after run", True) else ""

    print("\n─── Budgets (USD; blank = unlimited) ───\n")
    for key, label in (
        ("GENERATION_BUDGET", "Generation"),
        ("SEMIFORMALIZATION_BUDGET", "Semiformalization"),
        ("EXPLORATION_BUDGET", "Exploration"),
        ("SOURCE_SCAN_BUDGET", "Source scan"),
        ("FORMALIZATION_BUDGET", "Formalization"),
        ("CRITIC_BUDGET", "Critic"),
        ("VALIDATION_BUDGET", "Validation"),
    ):
        env_vars[key] = _prompt(f"{label} per-phase budget", env_vars[key])
    env_vars["SECONDARY_BUDGET"] = _prompt(
        "Secondary tier cumulative budget (hard cap)", env_vars["SECONDARY_BUDGET"]
    )

    print("\n─── Iteration / retry caps (blank = no cap) ───\n")
    env_vars["MAX_CRITIC_ITERATIONS"] = _prompt(
        "Max critic iterations", env_vars["MAX_CRITIC_ITERATIONS"]
    )
    env_vars["MAX_VALIDATION_ITERATIONS"] = _prompt(
        "Max validation iterations", env_vars["MAX_VALIDATION_ITERATIONS"]
    )
    env_vars["RESOLVER_MAX_RETRIES"] = _prompt(
        "Resolver max retries", env_vars["RESOLVER_MAX_RETRIES"]
    )

    print("\n─── Server ports ───\n")
    env_vars["FORUM_PORT"] = _prompt("Forum web UI port", env_vars["FORUM_PORT"])
    env_vars["LEAN_LSP_PORT"] = _prompt("Lean LSP MCP port", env_vars["LEAN_LSP_PORT"])

    print("\n─── Advanced (press enter to accept defaults) ───\n")
    env_vars["SDK_MESSAGE_IDLE_TIMEOUT"] = _prompt(
        "SDK message idle timeout (seconds)", env_vars["SDK_MESSAGE_IDLE_TIMEOUT"]
    )
    env_vars["MAX_LSP_RESTARTS_BEFORE_DEGRADE"] = _prompt(
        "Max lean-lsp restarts before degrading", env_vars["MAX_LSP_RESTARTS_BEFORE_DEGRADE"]
    )
    env_vars["TOOL_RESULT_MAX_CHARS"] = _prompt(
        "Tool-output truncation threshold (chars)", env_vars["TOOL_RESULT_MAX_CHARS"]
    )
    env_vars["CLAUDE_CODE_STREAM_CLOSE_TIMEOUT"] = _prompt(
        "SDK stream close timeout (ms)", env_vars["CLAUDE_CODE_STREAM_CLOSE_TIMEOUT"]
    )
    env_vars["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"] = (
        "true" if _prompt_bool("Enable experimental agent teams", False) else ""
    )


def run_setup(output_path: str = ".env", advanced: bool = False) -> None:
    """Run interactive setup to generate .env file."""
    print("\n╔══════════════════════════════════════════════════════════════╗")
    print("║                    Unity Agent Setup                         ║")
    print("╚══════════════════════════════════════════════════════════════╝")
    if not advanced:
        print("\nSimple setup. Most variables get sensible defaults from .env.example.")
        print("Run `unity setup --advanced` to be prompted for every knob.")

    env_vars = dict(SIMPLE_DEFAULTS)

    if advanced:
        _run_advanced(env_vars)
    else:
        _run_simple(env_vars)

    output_file = _write_env(output_path, env_vars)
    print(f"\n✓ Configuration saved to {output_file.absolute()}")
    if not env_vars.get("PRIMARY_API_KEY"):
        print("⚠ PRIMARY_API_KEY is empty — unity runs will fail until you set it.")
    print("\nNext: unity --source <source_file> --project <project_dir>\n")
